### PR TITLE
Release UI branches

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2076
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2079
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2081

## Note
You'll need a snap with branches. The easiest way to open a branch, that I've found, is to release a snap into a branch: `snapcraft release <snap_name> <revision_number> <branch (e.g. latest/stable/test)>`.

## QA
- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/<snap_name>/releases
- Release revisions to branches
- Close revisions in branches
- Promote to and from branches
- Drag things around
- Check the history of branch architectures
- Generally just click and drag things around as a normal user would

### CODE REVIEW

**Comment by Lukewh** [comment]
TODO:
 - [ ] Only promote to channels at lower risk levels (does not apply to branches in the same risk level - they can be inter-promoted)
 - [ ] Dragging from branch arch to non-branch arch doesn't update table on complete

**Comment by therealjuan** [comment]
LGTM

**Comment by kwm14** [comment]
## Design review
Looking good @Lukewh just a couple of minor thoughts 😉 

- [ ] Can we remove _italic_ on _close channel_ so text styling is consistent inside the table, we already highlight the background so I think that's enough of a cue...

Screenshot 2019-07-16 at 13 36 16

- [ ] Might not be possible but... when you hover the information icon can the tooltip sit under it, rather than be centered to the cell?

Screenshot 2019-07-16 at 13 39 45

**Comment by kwm14** [comment]
Updates LGTM 👍

**Pull request merged**
