### PR TITLE
Add snaps section

### LINKED ISSUE #3652: Build remove snaps functionality into snaps table

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Added snaps view to the brand store

## QA
- Go to https://snapcraft-io-3701.demos.haus/admin/ahnuP3quahti9vis8aiw/snaps
- Check that the checkboxes on the table work as expected (e.g. header one selects all, unchecking one un-checks header etc.)
- Click "Include snap" and use the search to find and add snaps
- Submit the form and check the snaps are in the table
- Checkboxes and remove snaps
- Check that it works as expected

## Issue
Fixes #3652, #3653

### CODE REVIEW

**Comment by jkfran** [comment]
All the QA steps are good, however, when I switch between different stores it takes a while to refresh and I can see snaps of the previous store.

**Comment by steverydz** [comment]
> Could you add some tests for this? 🙏

@petermakowski I'm coming back to tests after the main work is done - I've only got two more days to do the remaining sections.

**Comment by steverydz** [comment]
> All the QA steps are good, however, when I switch between different stores it takes a while to refresh and I can see snaps of the previous store.

@jkfran I've just updated so it clears the snaps table between store views and makes it clearer that it's loadings

**Review by jkfran — APPROVED** [review]
LGTM

**Pull request merged**
