### PR TITLE
Switch over to using canonicalwebteam.launchpad

### PR DESCRIPTION
**Pull request by nottrobin**
The code from webapp/api/launchpad.py was ported to
canonicalwebteam.launchpad, so it could be shared by ubuntu.com's
image builder stuff. It just means a few small interface changes.

Update this code to use that new module and interface, and remove
the old code from this codebase.

QA
--

Run the site, go to your publisher section, find a snap, go to the "builds" tab.

Try adding a repo to build from, and try triggering a build. Check everything works as expected.

### CODE REVIEW

**Comment by Lukewh** [comment]
"SnapBuilder" is a bad name, the module does more than just build snaps.

**Comment by nottrobin** [comment]
Like what?

**Comment by Lukewh** [comment]
It:
 - triggers snap builds
 - gets lists of builds for a snap
 - will get an individual build by id

Something like `SnapBuild` or `SnapBuilds` would be more accurate imo. I think thr `er` suffix makes it too specific.

**Comment by nottrobin** [comment]
Right fair enough.

I might just call it "Launchpad". I was trying to justify it existing alongside launchpadlib by pretending it had more specific purpose. But really it's just a collection of Launchpad API functions that we happen to find useful, and we find launchpadlib too confusing to use.

**Comment by nottrobin** [comment]
@Lukewh might this be acceptable to you now?

**Comment by jkfran** [comment]
@nottrobin Thank you!

**Pull request merged**
