### PR TITLE
Docs front end

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1051

## QA
- Ensure you have the search key available and set in your environment (or pass it to `./run` - see below)
- Pull the branch
- `./run --env SEARCH_API_KEY={the-api-key}`
- Visit http://0.0.0.0:8004/docs
- Use the docs
- Read the docs
- Become 1 with the docs
- Use the search
- Paginate through the search results
- Click on things
- Listen to your heart

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review
Looking good @Lukewh couldn't resist having a cheeky look 👀 

Could we update the hero background to inherit the same style as seen on /home and /store so that the pages become more consistent 😉 

Screenshot 2019-07-23 at 09 19 52

#winning

**Comment by kwm14** [comment]
@Lukewh lovely job 👍

**Comment by anthonydillon** [comment]
Looks good with a few comments:
- The docs a very slow locally (taking ~10s to connect).
- The URLs are not good. Is there a plan to map them to nice URLs before release?
- The Permission requests docs link in the navigation links to discourse
- Some pages are too narrow depending on the content:
Screenshot_2019-07-24 Snapcraft - Snaps are universal Linux packages
- The nav item "The /snap directory" 404'ed

**Comment by Lukewh** [comment]
Thanks @anthonydillon:

> Looks good with a few comments:
> 
>     * The docs a very slow locally (taking ~10s to connect).
Apparently this is normal, though they load ok for me :shrug:
>     * The URLs are not good. Is there a plan to map them to nice URLs before release?
There is a plan. I've also created https://github.com/canonical-web-and-design/snapcraft.io/issues/2103 to track it
>     * The Permission requests docs link in the navigation links to discourse
This is the same behaviour as on docs.snapcraft.io. I'm going to investigate whether that's intended or not.
>     * Some pages are too narrow depending on the content:
Fixed
>     * The nav item "The /snap directory" 404'ed
Created https://github.com/canonical-web-and-design/snapcraft.io/issues/2104 and @jpmartinspt is going to take a look

**Pull request merged**
