### PR TITLE
Revision cell changes to Release UI

### PR DESCRIPTION
**Pull request by steverydz**
## Done
- Added visual changes to the revision cells
- Add menus to promote or release revisions on click rather than drag

## QA
- Go to https://snapcraft-io-3892.demos.haus/danieltest-snap/releases
- Hover over a release or revision cell
- Check that there is a "Promote" or "Release" button
- Click the button and select an option from the menu
- Check that the revision/release has been released/promoted

## Issue
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2316

### CODE REVIEW

**Comment by steverydz** [comment]
@anasereijo This is ready for review now.

This PR only targets the changes listed in the description but please make comments on anything as this (hopefully) is the last of the PRs on this.

**Comment by anasereijo** [comment]
- [ ] is there a reason why are some cells and rows grey by default? on the new design, it should be grey when we hover it


- [ ] Replace arrow with text as per design 





- [ ] can you make the Channel col of each table slightly smaller so we can have more space for the rest?



- [ ] when I click the button the tooltip is on top of it. Is there a way to hide the tooltip if we click in the button?



- [ ] when promoting, the existing channel should be greyed out as per design




- [ ] can we hide the arrow and the dropdown, if there is no history?


- [ ] seems like there's still space to display a bit more of the text?


- [ ] when hovering the green cells (when there's a change to accept/cancel) we get the promote button under the cancel icon. Can we hide the promote button in these cases?


- [ ] the expanded cell design still looks like the older version. check new design

**Comment by steverydz** [comment]
@anasereijo this is ready for re-review. I've done everything except the grey hover issue as I'll fix that separately in this issue: https://github.com/canonical-web-and-design/snapcraft.io/issues/3898

**Comment by anasereijo** [comment]
- [ ] thanks for replacing the arrow with the text but I wonder if it's necessary to have the word 'channel' as it's taking space and I think it's quite self explanatory? Also, would it be possible to put the text in 2 lines and maybe smaller? as per original design?

Screenshot 2022-03-04 at 12 11 18
**Design:**
Screenshot 2022-03-04 at 12 12 09

- [ ] if there's nothing release can we remove the | ?
Screenshot 2022-03-04 at 12 10 57

- [ ] can't expand to see the history of any releases? The other day this charm had a few arrows to expand to see history, wondering why it's not possible now?
Screenshot 2022-03-04 at 12 15 42

- [ ] I do changes within the dropdown but I don't get the summary at the bottom with the cancel and save buttons?
Screenshot 2022-03-04 at 12 17 39

**Review by jkfran — APPROVED** [review]

**Pull request merged**
