### PR TITLE
IoT copy updates

### LINKED ISSUE #3581: snapcraft.io/iot copy updates
Copy updates requested by Holly on [snapcraft.io/iot](https://snapcraft.io/iot)

https://docs.google.com/document/d/1yfnQ5pXu5tDTG3M7Yv_gpjd894NUzSBKcvhB_pZqrMo/edit#

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Updated the copy on the IoT page as per [the copy doc](https://docs.google.com/document/d/1yfnQ5pXu5tDTG3M7Yv_gpjd894NUzSBKcvhB_pZqrMo/edit#)

## QA
- Go to https://snapcraft-io-3587.demos.haus/iot
- Check that the page matches [the copy doc](https://docs.google.com/document/d/1yfnQ5pXu5tDTG3M7Yv_gpjd894NUzSBKcvhB_pZqrMo/edit#)

## Issue
Fixes #3581 

## Screenshot
Screenshot_2021-06-28  Snapcraft - Fast and secure publishing for IoT (Internet of Things)

### CODE REVIEW

**Review by jkfran — APPROVED** [review]
LGTM

**Comment by long-chung** [comment]
Missing the last 2 snaps in the "Industrial IoT" section from the copy doc?

**Comment by steverydz** [comment]
@long-chung they're both there. The formatting of the copy doc makes it look like there's an extra row, but that text belongs to the cells above.

**Comment by long-chung** [comment]
Ah my bad. Looks good. +1

**Pull request merged**
