### PR TITLE
Use ModularTable for builds

### PR DESCRIPTION
**Pull request by bartaz**
## Done

Update builds table to use new `ModularTable` react compoenent.

## QA

- Pull the branch
- Run the site using the dotrun snap with `$ dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8004/ or [demo](https://snapcraft-io-3063.demos.haus)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check builds table of any snap, make sure it renders correctly

## Screenshots

Screenshot 2020-09-21 at 13 11 51

### CODE REVIEW

**Comment by solazio** [comment]
Got some console errors when started building:
image

**Comment by bartaz** [comment]
@solazio Oh, thanks, will have a look. From the error it seems that arch is empty... it is possible to have build without architecture?

**Comment by solazio** [comment]
Still says waiting for builds even though one architecture build has finished:
image

**Comment by solazio** [comment]
> @solazio Oh, thanks, will have a look. From the error it seems that arch is empty... it is possible to have build without architecture?

It seems that the architecture is in the first api return:
```
{
  "snap_builds": [
    {
      "arch_tag": "arm64", 
      "datebuilt": null, 
      "duration": null, 
      "id": "1128798", 
      "logs": null, 
      "queue_time": null, 
      "revision_id": null, 
      "status": "in_progress", 
      "title": "arm64 build of 50eb8c9ad11ac374b01b974888665fe2 snap package (together-we-win) in ubuntu bionic-updates"
    }, 
    {
      "arch_tag": "amd64", 
      "datebuilt": null, 
      "duration": null, 
      "id": "1128797", 
      "logs": null, 
      "queue_time": null, 
      "revision_id": null, 
      "status": "in_progress", 
      "title": "amd64 build of 50eb8c9ad11ac374b01b974888665fe2 snap package (together-we-win) in ubuntu bionic-updates"
    }, 
    {
      "arch_tag": "i386", 
      "datebuilt": null, 
      "duration": null, 
      "id": "1128796", 
      "logs": null, 
      "queue_time": null, 
      "revision_id": null, 
      "status": "in_progress", 
      "title": "i386 build of 50eb8c9ad11ac374b01b974888665fe2 snap package (together-we-win) in ubuntu bionic-updates"
    }
  ], 
  "total_builds": 3
}
```

**Comment by bartaz** [comment]
@solazio OK, thanks. I will QA it better to see why it shows "Waiting" when the builds are already there. I have an update to ModularTable waiting to be released in react-components, so I'll probably wait with this PR for that.

**Comment by solazio** [comment]
@bartaz is looking good, just a few comments:

- On mobile it looks odd. Perhaps we can `text-overflow: ellipsis;` to the "Result" column ... or maybe you have some other suggestion:

image

- The `Queue time` is not displayed

**Comment by bartaz** [comment]
Thanks @solazio. I updated the branch to fix the truncation and tooltip for queued builds.

**Review by solazio — APPROVED** [review]
Looks good :+1:. Thanks

**Pull request merged**
