### PR TITLE
Show error message for collaborators

### PR DESCRIPTION
**Pull request by jkfran**
## Done

- Show error message for collaborators

## Issue / Card

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/3117

## QA

- Pull the branch
- Run the site using the dotrun snap with `$ dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8004/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Link a Snap with a repository where you are a collaborator.
- Go to the settings tab and try to create the webhook.
- An error message should appear.

## Screenshots

image

### CODE REVIEW

**Comment by lilyvidenova** [comment]
@jkfran @tbille wasn't this the issue we said we can hopefully provide more specific errors based on the response we get from GH?

**Comment by jkfran** [comment]
> @jkfran @tbille wasn't this the issue we said we can hopefully provide more specific errors based on the response we get from GH?

Hey @lilyvidenova , I kept that in mind but the first response we get from GitHub is just a 404 when this happens. I had put a similar message to the one we currently have when linking a repo. Do you think the message is fine?

**Comment by lilyvidenova** [comment]
Yeah, if this is the most detail we can provide. :)

**Review by tbille — APPROVED** [review]
Looks good

**Pull request merged**
