### PR TITLE
New build page

### PR DESCRIPTION
**Pull request by Lukewh**
## Done

- Update build page with new messaging and design

## Issue / Card

Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1181

## QA

- Pull the branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8004/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Visit http://0.0.0.0:8004/build

### CODE REVIEW

**Comment by solazio** [comment]
the last image doesn't look too good on mobile - i.e. text is very small
image

**Comment by danielmutis** [comment]
I will make a mobile version of this @solazio

**Comment by danielmutis** [comment]
Here is the mobile version @solazio 
[Workflow.svg.zip](https://github.com/canonical-web-and-design/snapcraft.io/files/4492306/Workflow.svg.zip)

**Comment by Lukewh** [comment]
> Here is the mobile version @solazio
> [Workflow.svg.zip](https://github.com/canonical-web-and-design/snapcraft.io/files/4492306/Workflow.svg.zip)

don't know why you're pinging Ovi... but thanks :D

**Comment by danielmutis** [comment]
> don't know why you're pinging Ovi... but thanks :D

I don't know either.. it's the habit 😂

**Pull request merged**
