### PR TITLE
Update progressiveBar target % when props change

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2343
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2362

## QA
- Pull the branch
- `./run`
- Visit http://0.0.0.0:8004/snap_name/releases
- Progressively release a revision
- Once released, slide the progressive percentage bar
- Revert the changes
- The progressive release bar should reset to its previous value

### CODE REVIEW

**Comment by bartaz** [comment]
Something strange happens when you drag to 100% or further. Progress seems to be broken after that.

**Comment by Lukewh** [comment]
@bartaz ah! I imagine because at that point it is no longer classed as a "progressive release" so some of the UI updates to reflect that.

**Comment by bartaz** [comment]
There is an issue with pending update dissapearing after pausing:

progress

**Comment by bartaz** [comment]
Not sure if it's intended or not, but for sure not very clear - if you update the % and cancel before saving, and then save - both things are updated (% and pause), so you end up with changed % and save.

But tooltip on confirm only tells about pause.

Probably no need to fix it in this PR, but would be good to fix it separately.

**Comment by Lukewh** [comment]
> Not sure if it's intended or not, but for sure not very clear - if you update the % and cancel before saving, and then save - both things are updated (% and pause), so you end up with changed % and save.
> 
> But tooltip on confirm only tells about pause.
> 
> Probably no need to fix it in this PR, but would be good to fix it separately.

Ah minor change needed - will fix quickly here

**Comment by bartaz** [comment]
@Lukewh oh, cool, close this one when you do in this case: https://github.com/canonical-web-and-design/snapcraft.io/issues/2362 as I just added it

**Pull request merged**
