### PR TITLE
Update Python dependencies

### LINKED ISSUE #2935: Update Python dependencies

### PR DESCRIPTION
**Pull request by jkfran**
## Done

Update our Python dependencies

## Issue / Card

Fixes #2935

## QA

- Pull the branch
- Run the site using the dotrun snap with `$ dotrun`
- View the site locally in your web browser at: http://0.0.0.0:8004/
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Check the website works fine, especially tutorials and docs.

### CODE REVIEW

**Comment by tbille** [comment]
Seems there is an issue in tutorials section: 
image

**Comment by jkfran** [comment]
@tbille :thinking: to me your screenshot match with the current tutorial:
https://snapcraft.io/tutorials/snap-download

**Comment by tbille** [comment]
@jkfran oh yeah you are right. Is that the design or is it an issue?

**Comment by solazio** [comment]
@jkfran @tbille it's an issue, I noticed it yesterday as well. 
https://github.com/canonical-web-and-design/snapcraft.io/issues/2934

**Comment by solazio** [comment]
Docs search does not work on demo and locally I don't have the secret.
image

**Comment by jkfran** [comment]
@solazio Works for me, you need to add to your .env.local the token that I gave you yesterday. The one you are using for charmhub.io

**Pull request merged**
