### PR TITLE
Command consistency

### PR DESCRIPTION
**Pull request by therealjuan**
Fixes [#2048](https://github.com/canonical-web-and-design/snapcraft.io/issues/2048)

## QA Steps
1. Pull the branch or run the demo service
2. Check out all language guides include colons (:) before a command
3. Rinse and repeat at least 8 times
4. #watchhowmetricsgoup #winning

### CODE REVIEW

**Comment by kwm14** [comment]
**No labels. No review.** 
_Luke, May 2019_
_Karlos, June 2019_

**Labels. Labels. Labels everywhere!** 
_Juan_, Juan 2019

**Comment by therealjuan** [comment]
I just got a lapsus  and forgot about adding labels:

image


Don't get mad. Please.

**Comment by Lukewh** [comment]
https://snapcraft-io-canonical-web-and-design-pr-2185.run.demo.haus/first-snap/python linux doesn't have ":" before the code blocks

**Comment by therealjuan** [comment]
Thanks @Lukewh . I have updated the text according to your last comment and I hope this message finds you well. Best. Regards. Kind best. Kanye West.

**Pull request merged**
