### PR TITLE
Add listing page metrics fields

### PR DESCRIPTION
**Pull request by steverydz**
## Done
- Created sections for each group of listing form fields
- Added the "Additional information" form fields

## QA
- Go to https://snapcraft-io-4064.demos.haus/steve-test-snap/listing?show_react_listing=true (or any snap)
- Change the licenses and check that they work as expected

## Issue
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2651

### CODE REVIEW

**Comment by Lukewh** [comment]
I think maybe the dropdown should have a max-height and scroll :p!
image

**Comment by Lukewh** [comment]
Also, the items in the dropdown feel quite “tight” – maybe add a bit of padding in them? Possibly that's a UX / visual thing? Feels like on mobile might be hard to hit them with my chubby fingers.

**Comment by steverydz** [comment]
@Lukewh both fixed

**Review by Lukewh — APPROVED** [review]
:+1: LGTM

**Comment by Lukewh** [comment]
:partying_face:

**Pull request merged**
