### PR TITLE
Do not open lightbox in a new window on mobile

### LINKED ISSUE #2001: Clicking on screenshot should open a lightbox image viewer.
### Expected behaviour
When users clicks on an screenshot on the snap preview page they are expecting to get the image open in a lightbox image viewer.

### Steps to reproduce the problem
Visit  https://snapcraft.io/wonderwall click on any screenshot page will make user jump away from the website which is not a good practice (from SEO perspective too)

### Specs

- _URL:_ https://snapcraft.io/wonderwall
- _Operating system:_ Any
- _Browser:_ Any

### Solution
Implement any lightweight lightbox plugin to open screenshots on the same page with image navigation and close feature.

### PR DESCRIPTION
**Pull request by solazio**
## Done

- Fix lightbox opening in a new window on mobile

## Issue / Card

Fixes #2001 

## QA

- Pull the branch
- Run the site using the command `./run`
- View the site locally in your web browser at: http://0.0.0.0:8004/wonderwall
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- CLick on the images and see the lightbox appear. Do the same on mobile. The output should be similar. 

## Screenshots

image

image

### CODE REVIEW

**Comment by bartaz** [comment]
Just for the context.
We implemented opening images in separate tab on mobile on purpose.

Lightbox on mobile (especially small mobile) is very small. It often is smaller than a 'thumbnail' of screenshot. So it made no sense in opening the lightbox, because it was not making the images any bigger.

**Comment by solazio** [comment]
@bartaz, @Lukewh mentioned that, but from what I see now the image on mobile is a bit bigger than the "thumbnail" on portrait mode, however if you rotate you phone will be quite a lot bigger. So i consider it an improvement.
I don't know how small that phone needs to be so the "thumbnail" is bigger than in lightbox.

**Comment by bartaz** [comment]
If you go to iPhone 5 size it's quite small.

Screenshot 2020-04-29 at 12 50 13

But indeed in landscape it's better.

**Comment by solazio** [comment]
@bartaz iPhone 5 is a 🦕  lol

**Comment by barrymcgee** [comment]
That screenshot above for iPhone 5 also applies to 1st generation SE. Apple launched the second generation SE only last week and it's only marginally bigger...

Screenshot 2020-04-29 at 12 34 18

**Pull request merged**
