### PR TITLE
Publisher - Snap list

### PR DESCRIPTION
**Pull request by Lukewh**
Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2141

This will hopefully be temporary until we implement the new dashboard designs.

## QA
- Pull the branch
- `./run`
- Visit https://0.0.0.0:8004/snaps
- Ensure the list of snaps looks ok
- clicking on the name/ icon goes to the listing page
- To test various states:
  - No snaps - `/webapp/publisher/snaps/views.py:102` add 
```
user_snaps = {}
registered_snaps = []
```
  - 1 snap - edit `user_snaps = {}` to `user_snaps = {"snap_name": user_snaps["snap_name"]}`
  - new snap - below `user_snaps = {"snap_name": user_snaps["snap_name"]}` add `user_snaps["snap_name"]["is_new"] = True`

### CODE REVIEW

**Comment by bartaz** [comment]
Snap name is aligned differently from rest of the text in the table

Screenshot 2019-08-08 at 13 25 20

**Comment by Lukewh** [comment]
@bartaz added in another custom pattern... and updated the states (see QA instructions)

**Comment by therealjuan** [comment]
Nothing to comment. Speechless. Work as agreed. Lol

**Comment by kwm14** [comment]
Design LGTM 👍

**Comment by bartaz** [comment]
@Lukewh Graph tooltip is weirdly positioned.

There is similar problem on Metrics page that I started looking at. It seems to be (again) because of `u-fixed-width`.
And also now the graph title is in same container as graph itself, so while mouse position is counted only for graph, tooltip is positioned related to top of the heading.

I guess the easiest solution would be to use row and cols here, so graph (and only graph) is in `col-12`.

Screenshot 2019-08-09 at 08 03 49

**Comment by therealjuan** [comment]
👍 🎉 :shipit:  👍 🎉 :shipit:  LGTM 👍 🎉 :shipit:  👍 🎉 :shipit:  👍 🎉 :shipit:

**Pull request merged**
