### PR TITLE
Add build status column

### LINKED ISSUE #3309: JS Fetch JSON endpoint to show status

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Added a build status column to the snaps listing

## How to QA
- Go to https://snapcraft-io-3318.demos.haus/snaps
- Check that the table has a build status column

## Issue / Card
Fixes #3309, #3310

### CODE REVIEW

**Comment by jkfran** [comment]
@steverydz I'm not getting the column value for my snaps. I can see the following error in the JS console:
```
e.querySelector(...) is null
```

**Review by jkfran — APPROVED** [review]
It works fine, but I think before merging to master it needs a UX review? @danielmutis 

This is how it looks right now:
image

**Comment by danielmutis** [comment]
I tried it and it looks fine to me. It's strange that on demo most of my charms with builds don't show the latest builds (as if it wasn't build with github) and the status is unkown rather than Not Released (which is what we should show for charms we don't know where they come from).

The label in the table should be "Status" not "Build status" @steverydz

**Comment by steverydz** [comment]
@danielmutis I've made the changes we discussed earlier. If the build status is unknown it uses the release status.

https://snapcraft-io-3318.demos.haus/snaps

**Pull request merged**
