### PR TITLE
Add Snapcrafters publisher page

### PR DESCRIPTION
**Pull request by steverydz**
## Done
Created a publisher page for Snapcrafters 

## QA
- Go to https://snapcraft-io-3796.demos.haus/publisher/snapcrafters
- Compare to the other publisher pages:
  - https://snapcraft-io-3796.demos.haus/publisher/jetbrains
  - https://snapcraft-io-3796.demos.haus/publisher/kde
- Check it looks as it should

## Issue
Fixes [#2267](https://github.com/canonical-web-and-design/marketplace-tribe/issues/2267)

### CODE REVIEW

**Review by spencerbygraves — APPROVED** [review]

**Comment by anasereijo** [comment]
Looking good @steverydz, just a question:

- [ ] when clicking on the 'contact us' link doesn't do anything. I can see it's linked to a `mailto:` I wonder if this should link to a contact us page instead? Or is this common practice on snapcraft.io?

**Comment by anasereijo** [comment]
I also left a question for Holly in the copydoc

**Comment by steverydz** [comment]
@anasereijo 

> Looking good @steverydz, just a question:
> 
> * [ ]  when clicking on the 'contact us' link doesn't do anything. I can see it's linked to a `mailto:` I wonder if this should link to a contact us page instead? Or is this common practice on snapcraft.io?

That was what's requested in the copy doc. I don't think there is an actual page to link to so it should just open your mail client

**Comment by anasereijo** [comment]
LGTM

**Review by jkfran — APPROVED** [review]
+1

**Pull request merged**
