### PR TITLE
Add blog posts to homepage

### LINKED ISSUE #978: Featuring most recent blog posts on front page
The front page of snapcraft.io could better illustrate the activity around the platform. For example, we just launched Opera as a snap but you wouldn't know without clicking the blog tab.

Can we please feature the N most recent blog posts on the front page?

/cc @jamiebennett

### PR DESCRIPTION
**Pull request by steverydz**
## Done

Added last three snapcraft blog posts to the homepage

## Issue / Card

Fixes #978

## QA

https://snapcraft-io-3291.demos.haus
Make sure you get the last blog posts from snapcraft

### CODE REVIEW

**Comment by tbille** [comment]
Some notes from catchup with @lilyvidenova 
We should change:

- spacing seems wrong. We could follow the maas one: 
image

- First we should have title and then the date
- title could be 3 lines long
- Can we add the author name ?
```
Title of the blog article
15 December 2020 - Toto Bille
```

**Comment by steverydz** [comment]
@tbille @lilyvidenova the requested changes have been done

**Review by tbille — APPROVED** [review]

**Comment by lilyvidenova** [comment]
Hmmm, there seems to be no author on any of them:
image

Also, could we use the same style of heading as the next section?:
image

**Comment by steverydz** [comment]
@lilyvidenova maybe the demo is cached in your browser? It's definitely there, and I believe @tbille has seen it on the demo too?

**Comment by lilyvidenova** [comment]
A hard refresh did fix the authors' issue 🙌

**Comment by steverydz** [comment]
@lilyvidenova I've updated the headings

**Comment by lilyvidenova** [comment]
Looks good, thanks @steverydz 👍

**Pull request merged**
