### PR TITLE
Add invite member form to invites page

### LINKED ISSUE #3414: Add invite member button/form to invites page, to the right of the search box

### PR DESCRIPTION
**Pull request by steverydz**
## Done
- Added invite member form to invites page
- Refactored `modals.js` so it works with more than one modal per page

## QA
- Go to https://snapcraft-io-3418.demos.haus/admin/ahnuP3quahti9vis8aiw/members/invites
- Click the "Invite member" button on the top right of the screen
- Fill out the form and check that it works
- Go to https://snapcraft-io-3418.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage
- Click the "Invite member" button on the top right of the screen
- Fill out the form and check that it works

## Issue
Fixes #3414

### CODE REVIEW

**Comment by solazio** [comment]
@steverydz we should do some sort of field validation for the email, and make it required

**Comment by steverydz** [comment]
> @steverydz we should do some sort of field validation for the email, and make it required

@solazio I've just added the `required` attribute. The browser validates it as an email address. If we want to do something else that would be a wider discussion.

**Comment by solazio** [comment]
I don't know if you want to address this here, but on https://snapcraft-io-3418.demos.haus/admin/ahnuP3quahti9vis8aiw/members/manage when I open the modal, it shifts the navigations to the right by a few pixels.

**Review by solazio — APPROVED** [review]
Looks good :+1:. Thanks

**Comment by danielmutis** [comment]
@steverydz I think we should remove the option to invite members from the 'manage members' page. Only keep it in the invites page.

Also, the modal looks too narrow. Can we make it wider?

**Comment by steverydz** [comment]
@danielmutis Done. I made the modal a minimum width of 400px

**Pull request merged**
