### PR TITLE
Distro page snap details

### LINKED ISSUE #1951: Implement distro page snap details expandable box

### PR DESCRIPTION
**Pull request by bartaz**
Fixes #1951

Updates styling of snap details section of distro page.

### QA
- ./run or https://snapcraft-io-canonical-web-and-design-pr-1957.run.demo.haus/
- go to distro page of any snap (/install/SNAPNAME/arch or /instal/SNAPNAME/debian are available)
- snap details section should be collapsed by default
- click 'See more' to expand it
- check different snaps to see if various size descriptions, images, video, etc work

Screenshot 2019-06-04 at 16 20 40

### CODE REVIEW

**Comment by hughesjordan** [comment]
@bartaz is it possible to remove the border from the `.p-card` element replacing it with a box-shadow: 0px 4px 10px #11111140; or similar?

Also, the show more chevron, is it possible to change the colour within the URL supplied to be the same as the text?

**Comment by bartaz** [comment]
@hughesjordan I can change the style, but with every custom thing we are getting further away from Vanilla. I already needed to update padding of p-card for our design, if we get rid of border for shadow I guess it's not a p-card pattern anymore.

Can we leave purely visual updates for later (once we have whole page ready) and have a visual review with @kwm14 maybe?

**Comment by hughesjordan** [comment]
@bartaz sure sounds good, I'll add an issue so we don't forget

**Comment by hughesjordan** [comment]
@bartaz sorry, I see you already have one now 👍

**Comment by kwm14** [comment]
> @hughesjordan I can change the style, but with every custom thing, we are getting further away from Vanilla. I already needed to update padding of p-card for our design, if we get rid of the border for shadow I guess it's not a p-card pattern anymore.
> 
> Can we leave purely visual updates for later (once we have the whole page ready) and have a visual review with @kwm14 maybe?

@bartaz Sure thing, once you've completed the build let me know and I'll give a final design review 😃

**Pull request merged**
