### PR TITLE
Build release UI channel cell changes

### PR DESCRIPTION
**Pull request by steverydz**
## Done
- Show hover state on whole row when channel cell is hovered
- Change gear icon to small button which only shows on hover
- Changed colour of dragging state for the row

## QA
- Go to https://snapcraft-io-3864.demos.haus/danieltest-snap/releases
- Hover over the channel cell (first one) in the table
- The whole row should be highlighted
- A button should appear to promote or close the channel
- Drag the row and it should turn light blue

## Issue
Fixes https://github.com/canonical-web-and-design/marketplace-tribe/issues/2315

### CODE REVIEW

**Comment by steverydz** [comment]
@anasereijo Some of the promote and close channel buttons wrap a bit awkwardly. I'm not sure what to do about that?

**Comment by anasereijo** [comment]
when hovering I could only see the option for closing the channels, not promoting, but I suppose that is correct? In cases that we can promote I suppose it will display that dropdown, correct?

**Comment by anasereijo** [comment]
visual comment, but I think the dropdown doesn't look correct? seems like the dropdown is slightly over the button?

Screenshot 2022-01-20 at 15 50 01

see the vanilla pattern 

Screenshot 2022-01-20 at 15 49 18

**Comment by anasereijo** [comment]
> @anasereijo Some of the promote and close channel buttons wrap a bit awkwardly. I'm not sure what to do about that?
> 
> 

I can't replicate that on my laptop, but can you truncate the text as per the [design](https://zpl.io/2G3geMJ)?

Screenshot 2022-01-20 at 15 52 47

**Comment by steverydz** [comment]
@anasereijo this is ready to be reviewed again

**Comment by steverydz** [comment]
@anasereijo @jkfran this is ready for re-review now

**Comment by anasereijo** [comment]
LGTM

**Review by jkfran — APPROVED** [review]
LGTM

**Pull request merged**
