### PR TITLE
RHEL distro page

### PR DESCRIPTION
**Pull request by bartaz**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1133

Adds Red Hat Enterprise Linux distro page.

### QA

- ./run or https://snapcraft-io-canonical-web-and-design-pr-2314.run.demo.haus/
- go to /install/SNAP/rhel of any snap https://snapcraft-io-canonical-web-and-design-pr-2314.run.demo.haus/install/lxd/rhel
- try different snaps
- check if everything renders well
- check if install instructions are correct (https://snapcraft.io/docs/installing-snap-on-red-hat)
- go to any snap details page, check in distros list in the bottom includes Red Hat
- click on a link, make sure it goes to RHEL distro page

Screenshot 2019-10-17 at 13 45 13

Screenshot 2019-10-18 at 09 27 26

### CODE REVIEW

**Comment by kwm14** [comment]
Looking good @bartaz just one small change 😸 

Can we update the logo under the "Enable snaps..." section to the stacked version?

https://assets.ubuntu.com/v1/be89e41a-red-hat-2019-primary-stacked.svg

The reason being when you view on a smaller viewport it looks tiny and compared to other distros it doesn't look as prominent.

Screenshot 2019-10-17 at 16 04 23

**Comment by bartaz** [comment]
@kwm14 Done:

Screenshot 2019-10-18 at 08 59 36

**Comment by bartaz** [comment]
@Lukewh @kwm14 I also added it to the distros list on snaps page if you can have a look:

Screenshot 2019-10-18 at 09 27 26

**Comment by kwm14** [comment]
Thanks @bartaz design LGTM 👍

**Pull request merged**
