### PR TITLE
Update content for ABC testing

### PR DESCRIPTION
**Pull request by solazio**
## Done
- _Update content for ABC testing._
- _Redirect `/first/snap/<language>/create-account` to `/first/snap/<language>`_

## How to QA
- Visit the demo in your browser at https://snapcraft-io-3354.demos.haus
  - Or you can run the project locally using the [dotrun](https://snapcraft.io/dotrun) snap with `$ dotrun` and view it in your web browser at: http://0.0.0.0:8004/
  - If your demo doesn't work, read more about the [demoservice](https://discourse.ubuntu.com/t/demoservice/16862)
- Run through the following [QA steps](https://canonical-web-and-design.github.io/practices/workflow/qa-steps.html)
- Go to https://snapcraft-io-3354.demos.haus and select "python" from FSF and click continue. It should take you to https://snapcraft-io-3354.demos.haus/first-snap/python
- Go to https://snapcraft-io-3354.demos.haus/first-snap-2/python/create-account and compare to [design](https://app.zeplin.io/project/601000b327cc222b78024e00/screen/601001579046d20e25bec27d)
- Go to https://snapcraft-io-3354.demos.haus/first-snap-3/python/create-account and compare to [design](https://app.zeplin.io/project/601000b327cc222b78024e00/screen/60100157d6838d0b067913d7)
- Log out from your account, go to https://snapcraft-io-3354.demos.haus/first-snap-2/python and see that you will be asked to log in before you get to that page
- Log out from your account, go to https://snapcraft-io-3354.demos.haus/first-snap-3/python and see that you will be asked to log in before you get to that page

## Issue / Card
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1762

## Screenshots
[if relevant, include a screenshot]

### CODE REVIEW

**Comment by tbille** [comment]
https://snapcraft-io-3354.demos.haus/first-snap-2/python/linux/build-and-test

all the links a redirecting me to  first-snap (and not first-snap-2)

**Comment by solazio** [comment]
> https://snapcraft-io-3354.demos.haus/first-snap-2/python/linux/build-and-test
> 
> all the links a redirecting me to first-snap (and not first-snap-2)

That is correct. All the links are using first-snap, and Google optimiser will do the job of replacing first-snap with first-snap-2 or first-snap-3 in the url.

**Comment by tbille** [comment]
In the second and third flows can you just keep the steps 2 and 3  (register name  and push to store) in the last section:
image

https://snapcraft-io-3354.demos.haus/first-snap-2/pre-built/linux/push
https://snapcraft-io-3354.demos.haus/first-snap-3/pre-built/linux/push

Basically can you keep just this , and replace Step 2 -> Step 1  and Step 3 -> 2
image

**Review by tbille — APPROVED** [review]
ok seems good to me

**Pull request merged**
